export const testIds = {
  appLoader: {
    container: 'app-loader',
    inline: 'inline-app-loader',
  },
  appConfig: {
    apiKey: 'data-testid ac-api-key',
    apiUrl: 'data-testid ac-api-url',
    settingsTab: (id: string) => `data-testid ac-settings-tab-${id}`,
    settingsTabPanel: (id: string) => `data-testid ac-settings-tab-panel-${id}`,
    unsavedChangesNotice: 'data-testid ac-unsaved-changes-notice',
    maxTotalTokens: 'data-testid ac-max-total-tokens',
    submit: 'data-testid ac-submit-form',
    useBuiltInMCPToggle: 'data-testid ac-use-builtin-mcp-toggle',
    addMcpServerButton: 'data-testid ac-add-mcp-server',
    saveMcpServersButton: 'data-testid ac-save-mcp-servers',
    mcpServerCard: (id: string) => `data-testid ac-mcp-server-${id}`,
    mcpServerNameInput: (id: string) => `data-testid ac-mcp-server-name-${id}`,
    mcpServerUrlInput: (id: string) => `data-testid ac-mcp-server-url-${id}`,
    mcpServerRemoveButton: (id: string) => `data-testid ac-mcp-server-remove-${id}`,
    mcpServerAdvancedToggle: (id: string) => `data-testid ac-mcp-server-advanced-${id}`,
    mcpServerAddHeaderButton: (id: string) => `data-testid ac-mcp-server-add-header-${id}`,
    mcpServerHeaderKeyInput: (id: string, index: number) => `data-testid ac-mcp-server-header-key-${id}-${index}`,
    mcpServerHeaderValueInput: (id: string, index: number) => `data-testid ac-mcp-server-header-value-${id}-${index}`,
    mcpServerHeaderRemoveButton: (id: string, index: number) =>
      `data-testid ac-mcp-server-header-remove-${id}-${index}`,
    manageToolsButton: (id: string) => `data-testid ac-manage-tools-${id}`,
    manageToolsModal: 'data-testid ac-manage-tools-modal',
    manageToolsToolItem: (toolName: string) => `data-testid ac-manage-tool-item-${toolName}`,
    promptEditor: {
      system: 'ac-prompt-system',
      investigation: 'ac-prompt-investigation',
      performance: 'ac-prompt-performance',
    },
    displaySettings: 'data-testid ac-display-settings',
    kioskModeField: 'data-testid ac-kiosk-mode-field',
    kioskModeToggle: 'data-testid ac-kiosk-mode-toggle',
    chatPanelPositionField: 'data-testid ac-chat-panel-position-field',
    chatPanelPositionSelector: 'data-testid ac-chat-panel-position-selector',
    saveDisplaySettingsButton: 'data-testid ac-save-display-settings',
    serviceGraphMaxNodes: 'data-testid ac-service-graph-max-nodes',
    serviceGraphMaxEdges: 'data-testid ac-service-graph-max-edges',
    refreshServiceGraphButton: 'data-testid ac-refresh-service-graph',
    serviceGraphSummary: 'data-testid ac-service-graph-summary',
    saveServiceGraphSettingsButton: 'data-testid ac-save-service-graph-settings',
  },
  home: {
    container: 'data-testid home-container',
  },
  chat: {
    newChatButton: 'data-testid chat-new-chat-button',
    retryButton: 'data-testid chat-retry-button',
  },
  investigation: {
    error: 'data-testid investigation-error',
  },
};
